version: '3.8'
services:
  incident-service:
    build: .
    container_name: incident-service
    restart: always
    env_file: .env
    networks:
      - monitoring-network
    ports:
      - "5002:3004"

networks:
  monitoring-network:
    name: monitoring-network
    external: true
